
- name: jenkins-master
  hosts: all
  become: true

  tasks:

    - name: Ensure dependencies are installed
      package:
        name:
          - curl
          - initscripts
          - "{{ 'libselinux-python' if ansible_python['version']['major'] < 3 else 'python3-libselinux' }}"
        state: present

    - name: Ensure Java8 is installed
      package:
        name:
          - java-1.8.0-openjdk-devel
        state: present
